USE [master]
GO

/****** Object:  Database [SearchResults]    Script Date: 4/5/2019 12:28:11 PM ******/
CREATE DATABASE [SearchResults]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SearchResults', FILENAME = N'D:\Programs\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SearchResults.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SearchResults_log', FILENAME = N'D:\Programs\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SearchResults_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SearchResults] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SearchResults].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SearchResults] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SearchResults] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SearchResults] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SearchResults] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SearchResults] SET ARITHABORT OFF 
GO

ALTER DATABASE [SearchResults] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SearchResults] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SearchResults] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SearchResults] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SearchResults] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SearchResults] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SearchResults] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SearchResults] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SearchResults] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SearchResults] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SearchResults] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SearchResults] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SearchResults] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SearchResults] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SearchResults] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SearchResults] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SearchResults] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SearchResults] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SearchResults] SET  MULTI_USER 
GO

ALTER DATABASE [SearchResults] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SearchResults] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SearchResults] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SearchResults] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SearchResults] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SearchResults] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SearchResults] SET  READ_WRITE 
GO

